apiVersion: v1
kind: Service
metadata:
  name: jenkins-portal
  namespace: jenkins
spec:
  selector:
    name: jenkins
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  selector:
    name: jenkins
  ports:
    - protocol: TCP
      port: 50000
      nodePort: 50000
      targetPort: 50000
  type: NodePort
  


